lib/rumbl_web/router.ex
defmodule RumblWeb.Router do
  use RumblWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Rumbl.Auth, [repo: Rumbl.Repo]
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", RumblWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/users", UserController, only: [:index, :show, :new, :create]
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    get "/watch/:id", WatchController, :show
  end

  scope "/manage", RumblWeb do
    pipe_through [:browser, :authenticate_user]

    resources "/videos", VideoController
  end

  # Other scopes may use custom stacks.
  # scope "/api", RumblWeb do
  #   pipe_through :api
  # end
end

lib/rumbl/videos.ex
defmodule Rumbl.Videos do
  @moduledoc """
  The Videos context.
  """

  import Ecto.Query, warn: false
  alias Rumbl.Repo

  alias Rumbl.Videos.Video

  @doc """
  Returns the list of videos.

  ## Examples

      iex> list_videos()
      [%Video{}, ...]

  """
  def list_videos do
    Repo.all(Video)
  end

  @doc """
  Gets a single video.

  Raises `Ecto.NoResultsError` if the Video does not exist.

  ## Examples

      iex> get_video!(123)
      %Video{}

      iex> get_video!(456)
      ** (Ecto.NoResultsError)

  """
  def get_video!(id), do: Repo.get!(Video, id)

  @doc """
  Creates a video.

  ## Examples

      iex> create_video(%{field: value})
      {:ok, %Video{}}

      iex> create_video(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_video(attrs \\ %{}) do
    %Video{}
    |> Video.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a video.

  ## Examples

      iex> update_video(video, %{field: new_value})
      {:ok, %Video{}}

      iex> update_video(video, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_video(%Video{} = video, attrs) do
    video
    |> Video.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a Video.

  ## Examples

      iex> delete_video(video)
      {:ok, %Video{}}

      iex> delete_video(video)
      {:error, %Ecto.Changeset{}}

  """
  def delete_video(%Video{} = video) do
    Repo.delete(video)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking video changes.

  ## Examples

      iex> change_video(video)
      %Ecto.Changeset{source: %Video{}}

  """
  def change_video(%Video{} = video) do
    Video.changeset(video, %{})
  end
end

lib/rumbl/videos/video.ex
defmodule Rumbl.Videos.Video do
  use Ecto.Schema
  import Ecto.Changeset

  @primary_key {:id, Rumbl.Permalinks.Permalink, autogenerate: true}
  schema "videos" do
    field :descriptions, :string
    field :title, :string
    field :url, :string
    field :slug, :string

    belongs_to :user, Rumbl.User
    belongs_to :category, Rumbl.Categories.Category

    has_many :annotations, Rumbl.Annotations.Annotation

    timestamps()
  end

  @doc false
  def changeset(video, attrs) do
    video
    |> cast(attrs, [:url, :title, :descriptions, :category_id])
    |> validate_required([:url, :title, :descriptions])
    |> slugify_title()
    |> foreign_key_constraint(:category_id)
    |> assoc_constraint(:category)
  end

  defp slugify_title(changeset) do
    if title = get_change(changeset, :title) do
      put_change(changeset, :slug, slugify(title))
    else 
      changeset
    end
  end

  defp slugify(title) do
    title |> String.downcase |> String.replace(~r/[\W-]+/u, "-")
  end

  defimpl Phoenix.Param, for: Rumbl.Videos.Video  do
    def to_param(%{slug: slug, id: id}) do
      "#{id}-#{slug}"
    end
  end
end

lib/rumbl_web/controllers/video_controller.ex
defmodule RumblWeb.VideoController do
  use RumblWeb, :controller

  alias Rumbl.Videos
  alias Rumbl.Videos.Video
  alias Rumbl.Categories
  alias Rumbl.Categories.Category
  alias Rumbl.Repo

  plug :load_categories when action in [:new, :create, :edit, :update]

  def index(conn, _params, user) do
    videos = Repo.all(user_videos(user))
    render(conn, "index.html", videos: videos)
  end

  def new(conn, _params, user) do
    changeset =
      user
      |> Ecto.build_assoc(:videos)
      |> Videos.change_video()

    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"video" => video_params}, user) do
    changeset =
      user
      |> Ecto.build_assoc(:videos)
      |> Video.changeset(video_params)

    case Repo.insert(changeset) do
      {:ok, video} ->
        conn
        |> put_flash(:info, "Video created successfully.")
        |> redirect(to: Routes.video_path(conn, :show, video))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}, user) do
    video = Repo.get(user_videos(user), id)

    case video do
      nil ->
        conn
        |> put_flash(:error, "Video not found")
        |> redirect(to: Routes.video_path(conn, :index))

      video ->
        cat = Categories.get_category!(video.category_id)
        render(conn, "show.html", video: video, cat: cat)
    end
  end

  def edit(conn, %{"id" => id}, _user) do
    video = Videos.get_video!(id)
    changeset = Videos.change_video(video)
    render(conn, "edit.html", video: video, changeset: changeset)
  end

  def update(conn, %{"id" => id, "video" => video_params}, _user) do
    video = Videos.get_video!(id)

    case Videos.update_video(video, video_params) do
      {:ok, video} ->
        conn
        |> put_flash(:info, "Video updated successfully.")
        |> redirect(to: Routes.video_path(conn, :show, video))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", video: video, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}, user) do
    case Repo.get(user_videos(user), id) do
      nil ->
        conn
        |> put_flash(:error, "Video not found")
        |> redirect(to: Routes.video_path(conn, :index))

      video ->
        Videos.delete_video(video)
        conn
        |> put_flash(:info, "Video deleted successfully.")
        |> redirect(to: Routes.video_path(conn, :index))
    end
  end

  def action(conn, _) do
    apply(__MODULE__, action_name(conn), [conn, conn.params, conn.assigns.current_user])
  end

  def user_videos(user) do
    Ecto.assoc(user, :videos)
  end

  def load_categories(conn, _) do
    categories = Categories.list_categories()
    assign(conn, :categories, categories)
  end
end

lib/rumbl_web/views/video_view.ex
defmodule RumblWeb.VideoView do
  use RumblWeb, :view
end

lib/rumbl_web/templates/video/edit.html.eex
<h1>Edit Video</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.video_path(@conn, :update, @video)) %>

<span><%= link "Back", to: Routes.video_path(@conn, :index) %></span>

lib/rumbl_web/templates/video/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :url %>
  <%= text_input f, :url %>
  <%= error_tag f, :url %>

  <%= label f, :title %>
  <%= text_input f, :title %>
  <%= error_tag f, :title %>

  <%= label f, :descriptions %>
  <%= textarea f, :descriptions %>
  <%= error_tag f, :descriptions %>

  <%= label f, :category_id, "Category", class: 'control-label' %>
  <%= select f, :category_id, @categories, class: 'form-control', prompt: 'Select a Cat' %>
  <%= error_tag f, :category_id %>


  <div>
    <%= submit "Save" %>
  </div>
<% end %>

lib/rumbl_web/templates/video/index.html.eex
<h1>Listing Videos</h1>

<table>
  <thead>
    <tr>
      <th>Url</th>
      <th>Title</th>
      <th>Descriptions</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for video <- @videos do %>
    <tr>
      <td><%= video.url %></td>
      <td><%= video.title %></td>
      <td><%= video.descriptions %></td>

      <td>
        <%= link "Watch", to: Routes.watch_path(@conn, :show, video), class: "btn btn-default btn-xs" %>
        <%= link "Edit", to: Routes.video_path(@conn, :edit, video), class: "btn btn-default btn-xs" %>
        <%= link "Delete", to: Routes.video_path(@conn, :delete, video), 
                           method: :delete, 
                           data: [confirm: "Are you sure?"], 
                           class: "btn btn-default btn-xs" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Video", to: Routes.video_path(@conn, :new) %></span>

lib/rumbl_web/templates/video/new.html.eex
<h1>New Video</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.video_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.video_path(@conn, :index) %></span>

lib/rumbl_web/templates/video/show.html.eex
<h1>Show Video</h1>

<ul>

  <li>
    <strong>Url:</strong>
    <%= @video.url %>
  </li>

  <li>
    <strong>Title:</strong>
    <%= @video.title %>
  </li>

  <li>
    <strong>Descriptions:</strong>
    <%= @video.descriptions %>
  </li>

  <li>
    <strong>Category:</strong>
    <%= @cat.name %>
  </li>

   <li>
    <strong>slug:</strong>
    <%= @video.slug %>
  </li>
</ul>

<span><%= link "Edit", to: Routes.video_path(@conn, :edit, @video) %></span>
<span><%= link "Back", to: Routes.video_path(@conn, :index) %></span>