lib/rumbl_web/router.ex
defmodule RumblWeb.Router do
  use RumblWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Rumbl.Auth, [repo: Rumbl.Repo]
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", RumblWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/users", UserController, only: [:index, :show, :new, :create]
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    get "/watch/:id", WatchController, :show
  end

  scope "/manage", RumblWeb do
    pipe_through [:browser, :authenticate_user]

    resources "/videos", VideoController
  end

  # Other scopes may use custom stacks.
  # scope "/api", RumblWeb do
  #   pipe_through :api
  # end
end

lib/rumbl_web/views/layout_view.ex
defmodule RumblWeb.LayoutView do
  use RumblWeb, :view
end

lib/rumbl_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Rumbl · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>
    <header>
      <section class="container">
        <header>
          <nav>
            <ul>
              <%= if @current_user do %>
                <li><%= @current_user.username %></li> -
                <li><%= link "Home", to: "/" %></li> |                 
                <li>
                  <%= link "My Videos", to: Routes.video_path(@conn, :index) %>
                </li> |  
                <li>
                  <%= link "Log Out", to: Routes.session_path(@conn, :delete, @current_user), method: "delete" %>
                </li>
              <% else %>
                <%= link "Home", to: "/" %>
                <li><%= link "Register", to: Routes.user_path(@conn, :new) %></li>
                <li><%= link "Log in", to: Routes.session_path(@conn, :new) %></li>
              <% end %>
            </ul>
            <span class="phx-logo">
              <img src="<%= Routes.static_path(@conn, "/images/phoenix.png") %>" alt="Phoenix Framework Logo"/>
            </span>
          </nav>
        </header>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script>window.userToken = "<%= assigns[:user_token] %>"</script>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>